=== BISONNL/KV19/xsd/kv19-msg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Jan Koers (InTraffic B.V.) -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Copyright:	Dit document is eigendom van platform BISON onder de Stichting Connekt,-->
<!--            wordt geplubliceerd on de Creative Commons Licencsie by-nd/3.0/nl, zie -->
<!--            http://creativecommons.org/licemcmses/by-nd/3.0/nl                     -->
<!-- Opmerking: XSD is gebaseert op TMI8 koppelvlakken 19 versie 8.0.0.0(h)            -->
<!-- Version:   0.1 (concept)   (03-04-2009)                                           -->
<!--            0.2 (concept) (18-08-2009)                                             -->
<!--            0.3 (concept) (08-09-2009)                                             -->
<!--            0.4 (concept) (17-09-2009)                                             -->
<!--            0.5 (concept) (06-10-2009)                                             -->
<!-- History:                                                                          -->
<!--            0.1: initiele versie (8.1.0.0(a))                                      -->
<!--            0.2:bijgewerkte versie  (8.1.0.0(g))					                       	 -->
<!--            0.3:bijgewerkt versie 8.1.0.0(h)                                       -->
<!--            0.4:bijgewerkt versie 8.1.0.0(i)                                       -->
<!--            0.5:bijgewerkt versie 8.1.0.0(h)                                       -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv19/msg" xmlns:tmi8c="http://bison.connekt.nl/tmi8/kv19/core" targetNamespace="http://bison.connekt.nl/tmi8/kv19/msg" elementFormDefault="qualified">
	<xs:import namespace="http://bison.connekt.nl/tmi8/kv19/core" schemaLocation="kv19-core.xsd"/>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- TMI kv19 messages                                                                -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:element name="VV_TM_PUSH">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties"/>
				<xs:element name="KV19forecast" type="tmi8:KV19forecastType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="VV_TM_REQ">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="VV_TM_RES">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties" minOccurs="0"/>
				<xs:element name="ResponseCode" type="tmi8:ResponseCodeType"/>
				<xs:element name="ResponseError" type="tmi8:ResponseErrorType" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Dossiers: KV19forecast                                                           -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:complexType name="KV19forecastType">
		<xs:sequence>
			<xs:element name="KV19JOURNEY" type="tmi8:KV19JOURNEYType"/>
			<xs:element name="KV19EVENTS" type="tmi8:KV19EVENTSType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="KV19JOURNEYType">
		<xs:sequence>
			<xs:element name="daowcode" type="tmi8:daowcodeType"/>
			<xs:element name="lineplanningnumber" type="tmi8:lineplanningnumberType"/>
			<xs:element name="operatingday" type="tmi8:tmidateType"/>
			<xs:element name="journeynumber" type="tmi8:journeynumberType"/>
			<xs:element name="reinforcementnumber" type="tmi8:reinforcementnumberType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="KV19EVENTSType">
		<xs:sequence>
			<xs:choice>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="ASSIGNMENTPROPERTIES" type="tmi8:ASSIGNMENTPROPERTIESType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="ARRIVAL" type="tmi8:ARRIVALType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="DEPARTURE" type="tmi8:DEPARTUREType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="UPDATE" type="tmi8:UPDATEType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="SKIPPED" type="tmi8:SKIPPEDType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="HEARTBEAT" type="tmi8:HEARTBEATType" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="UNKNOWN" type="tmi8:UNKNOWNType" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:choice>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- POSINFO entities                                                                 -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:complexType name="ASSIGNMENTPROPERTIESType">
		<xs:sequence>
			<xs:sequence minOccurs="0">
				<xs:element name="userstopcode" type="tmi8:codeType"/>
				<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			</xs:sequence>
			<xs:element name="timestamp" type="tmi8:timestampType"/>
			<xs:element name="wheelchairaccessible" type="tmi8:wheelchairaccessibleType"/>
			<xs:element name="numberofcoaches" type="tmi8:numberofcoachesType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ARRIVALType">
		<xs:sequence>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			<xs:element name="timestamp" type="tmi8:timestampType"/>
			<xs:element name="recordedarrivaltime" type="tmi8:tmitimeType"/>
			<xs:element name="expecteddeparturetime" type="tmi8:tmitimeType" minOccurs="0"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DEPARTUREType">
		<xs:sequence>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			<xs:element name="timestamp" type="tmi8:timestampType"/>
			<xs:element name="recordeddeparturetime" type="tmi8:tmitimeType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="UPDATEType">
		<xs:sequence>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			<xs:element name="timestamp" type="tmi8:timestampType"/>
			<xs:element name="journeystoptype" type="tmi8:journeystoptypeType"/>
			<xs:element name="expectedarrivaltime" type="tmi8:tmitimeType"/>
			<xs:element name="expecteddeparturetime" type="tmi8:tmitimeType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SKIPPEDType">
		<xs:sequence>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			<xs:element name="timestamp" type="tmi8:timestampType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEARTBEATType">
		<xs:sequence>
			<xs:element name="timestamp" type="tmi8:timestampType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="UNKNOWNType">
		<xs:sequence>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:element name="passagesequencenumber" type="tmi8:passagesequencenumberType"/>
			<xs:element name="timestamp" type="tmi8:timestampType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Message property types                                                            -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:group name="MessageProperties">
		<xs:sequence>
			<xs:element name="SubscriberID" type="tmi8:SubscriberIDType"/>
			<xs:element name="Version" type="tmi8:VersionType"/>
			<xs:element name="DossierName" type="tmi8:DossierNameType"/>
			<xs:element name="Timestamp" type="tmi8:TimestampType"/>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="DossierNameType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="KV19forecast"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VersionType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SubscriberIDType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimestampType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="ResponseCodeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OK"/>
			<xs:enumeration value="NOK"/>
			<xs:enumeration value="SE"/>
			<xs:enumeration value="NA"/>
			<xs:enumeration value="PE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ResponseErrorType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Common entity types                                                               -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:simpleType name="daowcodeType">
		<xs:annotation id="E1">
			<xs:documentation xml:lang="nl">
				Een en ander bepaalt volgens BISON enumeratie E1.
				Op dit moment bekende waardes zijn:
				Vervoerders: ARR, VTN, CXX, GVB, HTM, NS, RET, SYNTUS, QBUZZ, TCR,
				Integrators:  ALGEMEEN, GOVI, RIG, SABIMOS, PRORAIL
				maar elke waarde is toegestaan
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="codeType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="passagesequencenumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="9999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmidateType">
		<xs:annotation>
			<xs:documentation>Format: YYYY-MM-DD</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:date">
			<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			<!--
			<xs:minLength value="10"/>
			<xs:maxLength value="10"/> -->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmitimeType">
		<xs:annotation>
			<xs:documentation>Format: HH:MM:SS / H:MM:SS</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="7"/>
			<xs:maxLength value="8"/>
			<xs:pattern value="(0|1|2|3|4|5|6|7|8|9|00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31):[012345][0123456789]:[012345][0123456789]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmidatetimeType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="timestampType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="vehicleidnumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="wheelchairaccessibleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ACCESSIBLE"/>
			<xs:enumeration value="NOTACCESSIBLE"/>
			<xs:enumeration value="UNKNOWN"/>
		</xs:restriction>
		<!-- E3 -->
	</xs:simpleType>
	<xs:simpleType name="journeystoptypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FIRST"/>
			<xs:enumeration value="INTERMEDIATE"/>
			<xs:enumeration value="LAST"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="reinforcementnumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="99"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="numberofcoachesType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="99"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="journeynumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="lineplanningnumberType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
</xs:schema>

=== BISONNL/KV19/xml/tmi8_forecast_8100-met-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<tmi8:VV_TM_PUSH xsi:schemaLocation="http://bison.connekt.nl/tmi8/kv19/msg kv19-msg.xsd" xmlns:tmi8c="http://bison.connekt.nl/tmi8/kv19/core" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv19/msg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tmi8:SubscriberID>a</tmi8:SubscriberID>
	<tmi8:Version>a</tmi8:Version>
	<tmi8:DossierName>KV19forecast</tmi8:DossierName>
	<tmi8:Timestamp>2001-12-17T09:30:47Z</tmi8:Timestamp>
	<tmi8:KV19forecast>
		<tmi8:KV19JOURNEY>
			<tmi8:daowcode>DATAOWNERC</tmi8:daowcode>
			<tmi8:lineplanningnumber>LINEPLANNI</tmi8:lineplanningnumber>
			<tmi8:operatingday>2009-09-07</tmi8:operatingday>
			<tmi8:journeynumber>012345</tmi8:journeynumber>
			<tmi8:reinforcementnumber>99</tmi8:reinforcementnumber>
			<tmi8c:delimiter/>
			<extrastufformoretriprelatedkeyssortofthingie>gjgg</extrastufformoretriprelatedkeyssortofthingie>
		</tmi8:KV19JOURNEY>
		<tmi8:KV19EVENTS>
			<tmi8:ARRIVAL>
				<tmi8:userstopcode>USERSTOPC</tmi8:userstopcode>
				<tmi8:passagesequencenumber>1234</tmi8:passagesequencenumber>
				<tmi8:timestamp>2009-09-07T09:30:47Z</tmi8:timestamp>
				<tmi8:recordedarrivaltime>23:59:00</tmi8:recordedarrivaltime>
				<tmi8:expecteddeparturetime>23:59:15</tmi8:expecteddeparturetime>
				<tmi8c:delimiter since="vandaag090909"/>
				<junker/>
				<morejunker/>
				<novervalidatedafterdelimiter>dhdskhfdskfhdsfk</novervalidatedafterdelimiter>
			</tmi8:ARRIVAL>
			<tmi8:ASSIGNMENTPROPERTIES>
				<tmi8:userstopcode>USERSTOPCO</tmi8:userstopcode>
				<tmi8:passagesequencenumber>9999</tmi8:passagesequencenumber>
				<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
				<tmi8:wheelchairaccessible>ACCESSIBLE</tmi8:wheelchairaccessible>
				<tmi8:numberofcoaches>99</tmi8:numberofcoaches>
				<tmi8c:delimiter since="String"/>
			</tmi8:ASSIGNMENTPROPERTIES>
			<tmi8:ARRIVAL>
				<tmi8:userstopcode>USERSTOPCO</tmi8:userstopcode>
				<tmi8:passagesequencenumber>9999</tmi8:passagesequencenumber>
				<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
				<tmi8:recordedarrivaltime>0:00:00</tmi8:recordedarrivaltime>
				<tmi8:expecteddeparturetime>0:00:00</tmi8:expecteddeparturetime>
				<tmi8c:delimiter since="String"/>
			</tmi8:ARRIVAL>
			<tmi8:DEPARTURE>
				<tmi8:userstopcode>USERSTOPCO</tmi8:userstopcode>
				<tmi8:passagesequencenumber>9999</tmi8:passagesequencenumber>
				<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
				<tmi8:recordeddeparturetime>0:00:00</tmi8:recordeddeparturetime>
				<tmi8c:delimiter since="String"/>
			</tmi8:DEPARTURE>
			<tmi8:UPDATE>
				<tmi8:userstopcode>USERSTOPCO</tmi8:userstopcode>
				<tmi8:passagesequencenumber>9999</tmi8:passagesequencenumber>
				<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
				<tmi8:journeystoptype>FIRST</tmi8:journeystoptype>
				<tmi8:expectedarrivaltime>0:00:00</tmi8:expectedarrivaltime>
				<tmi8:expecteddeparturetime>0:00:00</tmi8:expecteddeparturetime>
			</tmi8:UPDATE>
			<tmi8:UPDATE>
				<tmi8:userstopcode>bbbbbbbbbb</tmi8:userstopcode>
				<tmi8:passagesequencenumber>000001</tmi8:passagesequencenumber>
				<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
				<tmi8:journeystoptype>FIRST</tmi8:journeystoptype>
				<tmi8:expectedarrivaltime>00:00:00</tmi8:expectedarrivaltime>
				<tmi8:expecteddeparturetime>0:00:00</tmi8:expecteddeparturetime>
				<tmi8c:delimiter since="String"/>
			</tmi8:UPDATE>
			<tmi8:SKIPPED>
				<tmi8:userstopcode>USERSTOPCO</tmi8:userstopcode>
				<tmi8:passagesequencenumber>9999</tmi8:passagesequencenumber>
				<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
				<tmi8c:delimiter since="String"/>
			</tmi8:SKIPPED>
			<tmi8:UPDATE>
				<tmi8:userstopcode>bbbbbbbbbb</tmi8:userstopcode>
				<tmi8:passagesequencenumber>000001</tmi8:passagesequencenumber>
				<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
				<tmi8:journeystoptype>FIRST</tmi8:journeystoptype>
				<tmi8:expectedarrivaltime>00:00:00</tmi8:expectedarrivaltime>
				<tmi8:expecteddeparturetime>0:00:00</tmi8:expecteddeparturetime>
				<tmi8c:delimiter since="String"/>
			</tmi8:UPDATE>
			<tmi8:HEARTBEAT>
				<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
				<tmi8c:delimiter since="String"/>
			</tmi8:HEARTBEAT>
			<tmi8:UNKNOWN>
				<tmi8:userstopcode>USERSTOPCO</tmi8:userstopcode>
				<tmi8:passagesequencenumber>9999</tmi8:passagesequencenumber>
				<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
				<tmi8c:delimiter since="String"/>
			</tmi8:UNKNOWN>
			<tmi8:UNKNOWN>
				<tmi8:userstopcode>a</tmi8:userstopcode>
				<tmi8:passagesequencenumber>9987</tmi8:passagesequencenumber>
				<tmi8:timestamp>2009-09-07T23:00:00Z</tmi8:timestamp>
			</tmi8:UNKNOWN>
			<tmi8c:delimiter since="String"/>
		</tmi8:KV19EVENTS>
	</tmi8:KV19forecast>
	<tmi8:KV19forecast>
		<tmi8:KV19JOURNEY>
			<tmi8:daowcode>a</tmi8:daowcode>
			<tmi8:lineplanningnumber>b</tmi8:lineplanningnumber>
			<tmi8:operatingday>2009-09-09</tmi8:operatingday>
			<tmi8:journeynumber>1</tmi8:journeynumber>
			<tmi8:reinforcementnumber>0</tmi8:reinforcementnumber>
		</tmi8:KV19JOURNEY>
	</tmi8:KV19forecast>
</tmi8:VV_TM_PUSH>
